version: "3.7"
services:
  tensorflow-jupyter:
    build: ./tensorflow-jupyter
    ports:
      - ${JUPYTER_PORT}:8888
    volumes:
      - ./tensorflow-jupyter/notebooks:/tf/notebooks
      - ./tensorflow-jupyter/jupyter:/root/.jupyter
    privileged: true # for command dmesg. dmesg command required for debugging(ex: OOMemory)

  # UNCOMMENT IF YOU NEED TENSORFLOW WITHOUT JUPYTER NOTEBOOK
  # tensorflow:
  #   build: ./tensorflow
  #   volumes:
  #     - ./tensorflow/src:/tf/src
  #   privileged: true # for command dmesg. dmesg command required for debugging(ex: OOMemory)
