version: "3.7"
services:
  tensorflow:
    build: ./tensorflow
    image: tensorflow/tensorflow:latest-jupyter
    ports:
      - ${JUPYTER_PORT}:8888
    volumes:
      - ./tensorflow/notebooks:/tf/notebooks
    restart: always

