FROM tensorflow/tensorflow:latest-jupyter

RUN apt-get update -y
RUN apt-get upgrade -y
RUN apt-get autoremove -y

RUN pip install pandas
RUN pip install numpy
RUN pip install matplotlib
RUN pip install seaborn
RUN pip install sklearn
RUN pip install keras
